### ISSUE TITLE
바텀 네비게이션 뷰 아이콘 주위의 연보라 타원

### ISSUE THREAD

**Issue by todlf** [kakao-tech-campus-2nd-step3/Team21_Android#1]
## 어떤 버그인가요?

> 바텀 네비게이션 뷰 메뉴 아이콘 주위의 연보라 타원이 있어서 없애고 싶음

## 어떤 상황에서 발생한 버그인가요?

> 바텀 네비게이션 뷰를 만들자마자 자동으로 생김

## 예상 결과

> 바텀 네비게이션 뷰 메뉴 아이콘을 클릭해도 아이콘 주위에 연보라 타원이 생기지 않음

## 참고할만한 자료(선택)
![image](https://github.com/user-attachments/assets/7b1c95b0-c44d-4745-8183-c1e9be397e81)
`app:itemRippleColor` 속성을 바꿔봤는데 ripple 될 때만 색이 바뀜

**Comment by LeeOhHyung** [comment]
@todlf https://github.com/kakao-tech-campus-2nd-step3/Team21_Android/pull/8#discussion_r1770269984 이 PR에 코멘트 남겨두었습니다!
